name: bander
favicon: null
layout_spectrum: 0.75632
typography_spectrum: 0.56196
title: a digital junk drawer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8b8b9'
    - '#f59734'
    - '#373535'
    - '#6b6b6b'
    - '#929191'
  brandStrength: 0.36045613908208907
  lightness: 0.3908273121342063
  saturation: 0.6158355395309627
  rhythmicContrast: 0.16083988058380783
purpose: []
